LiveRoom: new Opa forum
-----------------------

Since it's the first post this year: Happy New Year everyone! We will have many exciting news for you in early 2012, but I decided to start off with announcing new Opa forum; Ladies and Gentelmen, let me present to you: _LiveRoom_.

image::img/live_room_png[link="http://forum.opalang.org"]

LiveRoom is a dedicated forum for discussions about Opa. It supports markup in the popular http://en.wikipedia.org/wiki/Markdown[Markdown] flavor (also used by http://stackoverflow.com[StackOverflow]) and real-time updates, so if two people happen to be posting to the same topic at the same time, the conversation can become chat-like.

For now, on top of LiveRoom, we will keep on offering support on the https://lists.owasp.org/mailman/listinfo/opa[mailing list] and on http://stackoverflow.com/questions/tagged/opa[StackOverflow], but over time we may replace the former with LiveRoom. So we encourage you to try it out today and are looking forward to hear what you think: just head to http://forum.opalang.org and let us be heard.

P.S. Yes, LiveRoom was developed in Opa :).
