They're talking about us...
---------------------------

It's been a bit over half a year since the source code of Opa was http://github.com/MLstate/opalang[released on GitHub] in June 2011. Since then the project gained quite a lot of attention, both in media and among developers, and I'll try to summarize that in this post.

At the end of July, shortly after the release, Morgan Hill consulting got interested in the project and wrote a http://www.morganhill.co.uk/cloud/opa-the-cloud-language-test-drive/[feature article on their blog] and WebAppers, a popular blog dedicated to top quality open source resources for web developers, made an http://www.webappers.com/2011/07/22/opa-the-scalable-open-source-cloud-language/[announcement about Opa] on their site.

August was a month of announcement on news aggregating sites: starting with http://www.osnews.com/comments/25102[OSnews] and then followed by well known http://lambda-the-ultimate.org/node/4336[Lambda the Ultimate] and http://developers.slashdot.org/story/11/08/27/2115210/Announcing-Opa-Making-Web-Programming-Transparent[Slashdot] and finally http://www.i-programmer.info/news/98-languages/2961-opa-a-unified-approach-to-web-programming.html[I Programmer], an online magazine for programmers. All of them received a fair amount of attention (including more than 27,000 reads for Lambda the Ultimate and over 250 comments for Slashdot).

Then in September we started getting noticed by newspapers. First InfoQ conducted an http://www.infoq.com/articles/Opa[extensive interview] with François-Régis Sinot, then the chief software architect of Opa. Then InfoWorld\'s Neil McAllister admitted he _`has been fascinated with Opa'_ and wrote an http://www.infoworld.com/d/application-development/introducing-opa-web-dev-language-rule-them-all-172060[article about it]. Finally JavaWorld, while handing out their Bossie awards (Best of Open Source Software), had this to say: _`And although it was too late for Bossie consideration, keep your eye on Opa, the new open source language that [...] may transform Web development'_.

In October we made a guest appearance on O'Reilly's http://www.josetteorama.com/technology/opa-web-programming-done-right-2/[josetteorama blog] and were selected as `Language of the Month' on the well-known http://drdobbs.com/web-development/231901249?queryText=Opa[Dr. Dobb's].

November brought us the conclusions of the http://opalang.org/challenge[Opa Developer Challenge]. We got many interesting submissions and had hard time selecting http://blog.opalang.org/2011/11/opa-developer-challenge-results.html[the winners]. The Challenge was also a great opportunity to get in touch with some Opa developers out there in the wild and we were very happy to hear that they had great things to say about Opa, such as:

{nbsp}{nbsp}_``Writing in Opa was super quick and fun! I don't think I could have written things as quickly in any other framework''_ +
{nbsp}{nbsp} -- Alok Menghrajani, Security Engineer at Facebook

{nbsp}{nbsp}_``Opa's type checking is simply amazing. [...] I think Opa will greatly change the future of web development''_ +
{nbsp}{nbsp} -- Tristan Sloughter, Co-Owner of Erlware, Erlang consulting organization

{nbsp}{nbsp}_``[Opa] has great abstractions to make an impressive start! Static typing [of Opa] helps catch most bugs at compile time rather than a stack trace at run time''_ +
{nbsp}{nbsp} -- Vimalkumar Jeyakumar, PhD in Computer Science at Stanford University

By the end of the year http://www.ohloh.net[Ohloh], online community platform that aims to map the landscape of open source software development, analysed the codebase of Opa and noted its _`very large, active development team'_, _`well-commented source code'_ and estimated the project cost at: $2,680,995. http://opalang.org[Opa's homepage] also received a lot of exposure and here were days when the number of visitors to the site would reach 10,000; so if you ever wondered whether an Opa backed site can sustain this kind of traffic, we can tell you: ``yes, it can'' :).

The new year started on a high note as we were again noted by InfoWorld which run an article http://www.infoworld.com/d/application-development/10-programming-languages-could-shake-it-181548?page=0,0[``10 programming languages that could shake up IT''], with Opa right there among those future IT shakers.

We hope 2012 will have a lot to offer for Opa and its users.  We'd like to take this opportunity to thank everyone who tried Opa or contributed to it -- we couldn't have done it without you! Please stay with us and help us grow by letting your fellow developers know how great Opa is for web development. The Opa team wishes you all the best in the New Year and a lot of happy development!
